import type { ErrorCode } from "@shared/types/ApiTypes";

/** Maps each ErrorCode to its HTTP status code. */
export const ERROR_HTTP_STATUS: Record<ErrorCode, number> = {
  VALIDATION_ERROR: 400,
  USER_SETTINGS_NOT_FOUND: 404,
  SETUP_ALREADY_COMPLETED: 409,
  DAILY_RECORD_NOT_FOUND: 404,
  ACTIVE_RECORD_NOT_FOUND: 404,
  DAILY_RECORD_ALREADY_EXISTS: 409,
  PREVIOUS_RECORD_STILL_OPEN: 409,
  DAILY_RECORD_ALREADY_CLOSED: 409,
  INVALID_DATE_FORMAT: 400,
  INVALID_TIME_FORMAT: 400,
  INVALID_TIME_RANGE: 400,
  INVALID_RECORD_TYPE: 400,
  CONFLICT: 409,
  INTERNAL_ERROR: 500,
};
